main: fr.cardi.mainPackage.Main
author: POPlol333
version: 1.1.3
name: UtilsAndFeatures
commands:
    admin-gui:
      description: Donne accès à un menu contenant tout les objets customisés !
      permission: UtilsAndFeatures.admin-gui
    setHealth:
      description: Permet de configurer manuellement la vie maximal du joueur cible !
      permission: UtilsAndFeatures.setHealth
    heal:
      description: Guérit le joueur cible !
      permission: UtilsAndFeatures.heal
    feed:
      description: Remplit la barre de nourriture du joueur cible !
      permission: UtilsAndFeatuers.feed
    setUnbreakable:
      description: Rend un objet incassable !
      permission: UtilsAndFeatures.setUnbreakable
    invsee:
      description: Permet de fouiller l'inventaire d'un joueur cible !
      permission: UtilsAndFeatures.invsee

